### ISSUE TITLE
commitlint 소개

### ISSUE THREAD

**Issue by ChangJoo-Park** [EndlessCreation/ec_homepage_front#7]
안녕하세요 18기 박창주입니다

[커밋 스타일 가이드](https://github.com/EndlessCreation/ec_homepage_front/wiki/02.-Commit-Style-Guide) 를 보고 이슈 남깁니다.

아직 프로젝트 저장소에 파일이 없어서 Pull Requests 를 남기지는 않았는데요 
프로젝트를 만드실 때 [commitlint](https://commitlint.js.org) 와 [husky](https://typicode.github.io/husky) 를 추가해서 커밋 스타일 가이드와 다른 커밋을 하지 못하도록 막을 수 있습니다.

**Comment by InHyeok-J** [comment]
선배님 좋은 정보 알려주셔서 감사합니다! 개발할때 적용해서 해보겠습니다!

**Comment by heechokim** [comment]
안녕하세요 27기 김초희입니다!

이슈 남겨주셔서 감사합니다!! 회의 때 알려주신 것 이야기 나눠보고 적용해보겠습니다.
앞으로도 관심 가져주시면 정말 정말 감사하겠습니다😀

**Comment by ChangJoo-Park** [comment]
네 좋은 프로젝트 경험이 되셨으면 좋을 것 같아요 종종 구경하면서 도움이 될  수 있는 부분 있으면 도와드릴게요

되도록이면 제가 의견을 적어두어도 그냥 그러려니 하고 해보고싶은 방향으로 했으면 좋겠어요 응원합니다 🏃
